
import LandingFooter from '@/components/layout/LandingFooter';
import LandingHeader from '@/components/layout/LandingHeader';

export default function TermsOfServicePage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <LandingHeader />

      <main className="flex-1 py-16 md:py-24">
        <div className="container mx-auto max-w-3xl px-4">
          <div className="prose prose-lg dark:prose-invert mx-auto">
            <h1>Terms of Service</h1>
            <p className="lead">
              Welcome to JobTrack. These Terms of Service ("Terms") govern your
              use of our application and services. By using JobTrack, you agree
              to these Terms.
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By creating an account and using our services, you confirm that
              you have read, understood, and agree to be bound by these Terms.
              If you do not agree with these Terms, you may not use the JobTrack
              application.
            </p>

            <h2>2. Use of the Service</h2>
            <p>
              JobTrack provides a suite of tools to help you manage your job
              search. You agree to use our services for their intended purpose
              and in compliance with all applicable laws. You must be at least
              16 years old to use JobTrack.
            </p>

            <h2>3. AI-Powered Features</h2>
            <p>
              Our application uses generative AI models (e.g., Google's Gemini)
              to provide features like resume feedback and cover letter
              generation.
            </p>
            <ul>
              <li>
                You are responsible for the content you provide (e.g., resume
                text, job descriptions).
              </li>
              <li>
                The AI-generated content is provided as a suggestion and should
                be reviewed carefully. JobTrack is not responsible for any
                inaccuracies, errors, or omissions in the content generated by
                the AI.
              </li>
              <li>
                The use of AI features is subject to the terms and policies of
                the underlying AI model providers.
              </li>
            </ul>

            <h2>4. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account and password. You agree to accept responsibility for all
              activities that occur under your account. You must notify us
              immediately of any unauthorized use of your account.
            </p>

            <h2>5. User Content</h2>
            <p>
              You retain full ownership of the data you create and upload to
              JobTrack, including your application details, resume content, and
              notes. We do not claim any ownership rights over your content. By
              using our service, you grant us a limited license to store,
              process, and display your content solely for the purpose of
              providing the service to you.
            </p>
            
            <h2>6. Prohibited Conduct</h2>
            <p>You agree not to:</p>
            <ul>
                <li>Use the service for any illegal purpose or in violation of any local, state, national, or international law.</li>
                <li>Attempt to reverse-engineer, decompile, or otherwise discover the source code of the application.</li>
                <li>Upload any content that is malicious, defamatory, or infringes on the rights of others.</li>
                <li>Interfere with the security-related features of the service.</li>
            </ul>


            <h2>7. Termination</h2>
            <p>
              We may suspend or terminate your access to the service at any time,
              without prior notice or liability, for any reason, including if
              you breach these Terms. You can terminate your account at any
              time from your profile settings page, which will result in the
              permanent deletion of your data.
            </p>

            <h2>8. Disclaimers</h2>
            <p>
              The JobTrack service is provided "as is" and "as available" without
              warranties of any kind. We do not guarantee that the service will
              be uninterrupted, secure, or free of errors.
            </p>

            <h2>9. Limitation of Liability</h2>
            <p>
              In no event shall JobTrack be liable for any indirect, incidental,
              special, consequential, or punitive damages arising out of or in
              connection with your use of the service.
            </p>

            <h2>10. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will
              provide notice of any significant changes. By continuing to use
              the service after changes have been made, you agree to be bound by
              the revised Terms.
            </p>

            <h2>11. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at
              terms@jobtrack.app.
            </p>

            <p>
              <em>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</em>
            </p>
          </div>
        </div>
      </main>
      <LandingFooter />
    </div>
  );
}
